# Generated by Django 2.1.5 on 2019-01-16 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wd_num', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=64)),
                ('sex', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Read',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wd_num', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=10)),
                ('group_name', models.CharField(max_length=200)),
                ('book_name', models.CharField(max_length=200)),
                ('target', models.CharField(max_length=200)),
                ('operation', models.CharField(max_length=10)),
                ('pay_type', models.CharField(max_length=10)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='guest',
            name='read_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign.Read'),
        ),
        migrations.AlterUniqueTogether(
            name='guest',
            unique_together={('read_id', 'phone')},
        ),
    ]
